### ISSUE TITLE
Examples fail to run: "Cannot find module 'inline-style-prefixer/static/createPrefixer'"

### ISSUE THREAD

**Issue by omerzach** [Khan/aphrodite#250]
```
Omers-MacBook-Pro:code omer$ npm -v
4.2.0
Omers-MacBook-Pro:code omer$ git clone git@github.com:Khan/aphrodite.git
Cloning into 'aphrodite'...
remote: Counting objects: 872, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 872 (delta 0), reused 1 (delta 0), pack-reused 861
Receiving objects: 100% (872/872), 439.29 KiB | 0 bytes/s, done.
Resolving deltas: 100% (501/501), done.
Omers-MacBook-Pro:code omer$ cd aphrodite/examples
Omers-MacBook-Pro:examples omer$ npm install && npm run examples
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> fsevents@1.1.2 install /Users/omer/code/aphrodite/examples/node_modules/fsevents
> node install

[fsevents] Success: "/Users/omer/code/aphrodite/examples/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node" is installed via remote
/Users/omer/code/aphrodite/examples
├─┬ babel@5.8.38
│ ├─┬ chokidar@1.7.0
│ │ ├─┬ anymatch@1.3.0
│ │ │ └── arrify@1.0.1
│ │ ├── async-each@1.0.1
│ │ ├─┬ fsevents@1.1.2
│ │ │ ├── nan@2.6.2
│ │ │ └─┬ node-pre-gyp@0.6.36
│ │ │   ├─┬ mkdirp@0.5.1
│ │ │   │ └── minimist@0.0.8
│ │ │   ├─┬ nopt@4.0.1
│ │ │   │ ├── abbrev@1.1.0
│ │ │   │ └─┬ osenv@0.1.4
│ │ │   │   ├── os-homedir@1.0.2
│ │ │   │   └── os-tmpdir@1.0.2
│ │ │   ├─┬ npmlog@4.1.0
│ │ │   │ ├─┬ are-we-there-yet@1.1.4
│ │ │   │ │ └── delegates@1.0.0
│ │ │   │ ├── console-control-strings@1.1.0
│ │ │   │ ├─┬ gauge@2.7.4
│ │ │   │ │ ├── aproba@1.1.1
│ │ │   │ │ ├── has-unicode@2.0.1
│ │ │   │ │ ├── object-assign@4.1.1
│ │ │   │ │ ├── signal-exit@3.0.2
│ │ │   │ │ ├─┬ string-width@1.0.2
│ │ │   │ │ │ ├── code-point-at@1.1.0
│ │ │   │ │ │ └─┬ is-fullwidth-code-point@1.0.0
│ │ │   │ │ │   └── number-is-nan@1.0.1
│ │ │   │ │ ├─┬ strip-ansi@3.0.1
│ │ │   │ │ │ └── ansi-regex@2.1.1
│ │ │   │ │ └── wide-align@1.1.2
│ │ │   │ └── set-blocking@2.0.0
│ │ │   ├─┬ rc@1.2.1
│ │ │   │ ├── deep-extend@0.4.2
│ │ │   │ ├── ini@1.3.4
│ │ │   │ ├── minimist@1.2.0
│ │ │   │ └── strip-json-comments@2.0.1
│ │ │   ├─┬ request@2.81.0
│ │ │   │ ├── aws-sign2@0.6.0
│ │ │   │ ├── aws4@1.6.0
│ │ │   │ ├── caseless@0.12.0
│ │ │   │ ├─┬ combined-stream@1.0.5
│ │ │   │ │ └── delayed-stream@1.0.0
│ │ │   │ ├── extend@3.0.1
│ │ │   │ ├── forever-agent@0.6.1
│ │ │   │ ├─┬ form-data@2.1.4
│ │ │   │ │ └── asynckit@0.4.0
│ │ │   │ ├─┬ har-validator@4.2.1
│ │ │   │ │ ├─┬ ajv@4.11.8
│ │ │   │ │ │ ├── co@4.6.0
│ │ │   │ │ │ └─┬ json-stable-stringify@1.0.1
│ │ │   │ │ │   └── jsonify@0.0.0
│ │ │   │ │ └── har-schema@1.0.5
│ │ │   │ ├─┬ hawk@3.1.3
│ │ │   │ │ ├── boom@2.10.1
│ │ │   │ │ ├── cryptiles@2.0.5
│ │ │   │ │ ├── hoek@2.16.3
│ │ │   │ │ └── sntp@1.0.9
│ │ │   │ ├─┬ http-signature@1.1.1
│ │ │   │ │ ├── assert-plus@0.2.0
│ │ │   │ │ ├─┬ jsprim@1.4.0
│ │ │   │ │ │ ├── assert-plus@1.0.0
│ │ │   │ │ │ ├── extsprintf@1.0.2
│ │ │   │ │ │ ├── json-schema@0.2.3
│ │ │   │ │ │ └── verror@1.3.6
│ │ │   │ │ └─┬ sshpk@1.13.0
│ │ │   │ │   ├── asn1@0.2.3
│ │ │   │ │   ├── assert-plus@1.0.0
│ │ │   │ │   ├── bcrypt-pbkdf@1.0.1
│ │ │   │ │   ├─┬ dashdash@1.14.1
│ │ │   │ │   │ └── assert-plus@1.0.0
│ │ │   │ │   ├── ecc-jsbn@0.1.1
│ │ │   │ │   ├─┬ getpass@0.1.7
│ │ │   │ │   │ └── assert-plus@1.0.0
│ │ │   │ │   ├── jodid25519@1.0.2
│ │ │   │ │   ├── jsbn@0.1.1
│ │ │   │ │   └── tweetnacl@0.14.5
│ │ │   │ ├── is-typedarray@1.0.0
│ │ │   │ ├── isstream@0.1.2
│ │ │   │ ├── json-stringify-safe@5.0.1
│ │ │   │ ├─┬ mime-types@2.1.15
│ │ │   │ │ └── mime-db@1.27.0
│ │ │   │ ├── oauth-sign@0.8.2
│ │ │   │ ├── performance-now@0.2.0
│ │ │   │ ├── qs@6.4.0
│ │ │   │ ├── safe-buffer@5.0.1
│ │ │   │ ├── stringstream@0.0.5
│ │ │   │ ├─┬ tough-cookie@2.3.2
│ │ │   │ │ └── punycode@1.4.1
│ │ │   │ ├── tunnel-agent@0.6.0
│ │ │   │ └── uuid@3.0.1
│ │ │   ├─┬ rimraf@2.6.1
│ │ │   │ └─┬ glob@7.1.2
│ │ │   │   ├── fs.realpath@1.0.0
│ │ │   │   ├── inflight@1.0.6
│ │ │   │   ├─┬ minimatch@3.0.4
│ │ │   │   │ └─┬ brace-expansion@1.1.7
│ │ │   │   │   ├── balanced-match@0.4.2
│ │ │   │   │   └── concat-map@0.0.1
│ │ │   │   └── path-is-absolute@1.0.1
│ │ │   ├── semver@5.3.0
│ │ │   ├─┬ tar@2.2.1
│ │ │   │ ├── block-stream@0.0.9
│ │ │   │ ├─┬ fstream@1.0.11
│ │ │   │ │ └── graceful-fs@4.1.11
│ │ │   │ └── inherits@2.0.3
│ │ │   └─┬ tar-pack@3.4.0
│ │ │     ├─┬ debug@2.6.8
│ │ │     │ └── ms@2.0.0
│ │ │     ├── fstream-ignore@1.0.5
│ │ │     ├─┬ once@1.4.0
│ │ │     │ └── wrappy@1.0.2
│ │ │     ├─┬ readable-stream@2.2.9
│ │ │     │ ├── buffer-shims@1.0.0
│ │ │     │ ├── core-util-is@1.0.2
│ │ │     │ ├── isarray@1.0.0
│ │ │     │ ├── process-nextick-args@1.0.7
│ │ │     │ ├── string_decoder@1.0.1
│ │ │     │ └── util-deprecate@1.0.2
│ │ │     └── uid-number@0.0.6
│ │ ├── glob-parent@2.0.0
│ │ ├── inherits@2.0.3
│ │ ├─┬ is-binary-path@1.0.1
│ │ │ └── binary-extensions@1.8.0
│ │ ├─┬ is-glob@2.0.1
│ │ │ └── is-extglob@1.0.0
│ │ └─┬ readdirp@2.1.0
│ │   ├── minimatch@3.0.4
│ │   └── set-immediate-shim@1.0.1
│ ├─┬ commander@2.9.0
│ │ └── graceful-readlink@1.0.1
│ ├── convert-source-map@1.5.0
│ ├── fs-readdir-recursive@0.1.2
│ ├─┬ glob@5.0.15
│ │ ├─┬ inflight@1.0.6
│ │ │ └── wrappy@1.0.2
│ │ └── once@1.4.0
│ ├── lodash@3.10.1
│ ├─┬ output-file-sync@1.1.2
│ │ ├── graceful-fs@4.1.11
│ │ └── object-assign@4.1.1
│ ├── path-exists@1.0.0
│ ├── path-is-absolute@1.0.1
│ ├── slash@1.0.0
│ └── source-map@0.5.6
├─┬ babel-core@5.8.38
│ ├── babel-plugin-constant-folding@1.0.1
│ ├── babel-plugin-dead-code-elimination@1.0.2
│ ├── babel-plugin-eval@1.0.1
│ ├── babel-plugin-inline-environment-variables@1.0.1
│ ├── babel-plugin-jscript@1.0.4
│ ├── babel-plugin-member-expression-literals@1.0.1
│ ├── babel-plugin-property-literals@1.0.1
│ ├── babel-plugin-proto-to-assign@1.0.4
│ ├── babel-plugin-react-constant-elements@1.0.3
│ ├── babel-plugin-react-display-name@1.0.3
│ ├── babel-plugin-remove-console@1.0.1
│ ├── babel-plugin-remove-debugger@1.0.1
│ ├── babel-plugin-runtime@1.0.7
│ ├─┬ babel-plugin-undeclared-variables-check@1.0.2
│ │ └── leven@1.0.2
│ ├── babel-plugin-undefined-to-void@1.1.6
│ ├── babylon@5.8.38
│ ├── bluebird@2.11.0
│ ├─┬ chalk@1.1.3
│ │ ├── ansi-styles@2.2.1
│ │ ├── escape-string-regexp@1.0.5
│ │ ├── has-ansi@2.0.0
│ │ └── supports-color@2.0.0
│ ├── core-js@1.2.7
│ ├─┬ debug@2.6.8
│ │ └── ms@2.0.0
│ ├─┬ detect-indent@3.0.1
│ │ ├── get-stdin@4.0.1
│ │ └── minimist@1.2.0
│ ├── esutils@2.0.2
│ ├── globals@6.4.1
│ ├─┬ home-or-tmp@1.0.0
│ │ ├── os-tmpdir@1.0.2
│ │ └── user-home@1.1.1
│ ├─┬ is-integer@1.0.7
│ │ └─┬ is-finite@1.0.2
│ │   └── number-is-nan@1.0.1
│ ├── js-tokens@1.0.1
│ ├── json5@0.4.0
│ ├─┬ minimatch@2.0.10
│ │ └─┬ brace-expansion@1.1.8
│ │   ├── balanced-match@1.0.0
│ │   └── concat-map@0.0.1
│ ├── private@0.1.7
│ ├─┬ regenerator@0.8.40
│ │ ├─┬ commoner@0.10.8
│ │ │ ├─┬ detective@4.5.0
│ │ │ │ ├── acorn@4.0.13
│ │ │ │ └── defined@1.0.0
│ │ │ ├── iconv-lite@0.4.18
│ │ │ ├── q@1.5.0
│ │ │ └─┬ recast@0.11.23
│ │ │   ├── ast-types@0.9.6
│ │ │   └── esprima@3.1.3
│ │ ├─┬ defs@1.1.1
│ │ │ ├─┬ alter@0.2.0
│ │ │ │ └── stable@0.1.6
│ │ │ ├── ast-traverse@0.1.1
│ │ │ ├── breakable@1.0.0
│ │ │ ├── simple-fmt@0.1.0
│ │ │ ├── simple-is@0.2.0
│ │ │ ├── stringmap@0.2.2
│ │ │ ├── stringset@0.2.1
│ │ │ ├── tryor@0.1.2
│ │ │ └─┬ yargs@3.27.0
│ │ │   ├─┬ os-locale@1.4.0
│ │ │   │ └─┬ lcid@1.0.0
│ │ │   │   └── invert-kv@1.0.0
│ │ │   ├── window-size@0.1.4
│ │ │   └── y18n@3.2.1
│ │ ├── esprima-fb@15001.1001.0-dev-harmony-fb
│ │ ├─┬ recast@0.10.33
│ │ │ └── ast-types@0.8.12
│ │ └── through@2.3.8
│ ├─┬ regexpu@1.3.0
│ │ ├── esprima@2.7.3
│ │ ├── regenerate@1.3.2
│ │ ├── regjsgen@0.2.0
│ │ └─┬ regjsparser@0.1.5
│ │   └── jsesc@0.5.0
│ ├── repeating@1.1.3
│ ├─┬ resolve@1.3.3
│ │ └── path-parse@1.0.5
│ ├── shebang-regex@1.0.0
│ ├─┬ source-map-support@0.2.10
│ │ └─┬ source-map@0.1.32
│ │   └── amdefine@1.0.1
│ ├── to-fast-properties@1.0.3
│ ├── trim-right@1.0.1
│ └── try-resolve@1.0.1
├─┬ babel-loader@5.4.2
│ ├─┬ loader-utils@0.2.17
│ │ ├── big.js@3.1.3
│ │ ├── emojis-list@2.1.0
│ │ └── json5@0.5.1
│ └── object-assign@3.0.0
├─┬ express@4.15.3
│ ├─┬ accepts@1.3.3
│ │ ├─┬ mime-types@2.1.15
│ │ │ └── mime-db@1.27.0
│ │ └── negotiator@0.6.1
│ ├── array-flatten@1.1.1
│ ├── content-disposition@0.5.2
│ ├── content-type@1.0.2
│ ├── cookie@0.3.1
│ ├── cookie-signature@1.0.6
│ ├── debug@2.6.7
│ ├── depd@1.1.0
│ ├── encodeurl@1.0.1
│ ├── escape-html@1.0.3
│ ├── etag@1.8.0
│ ├─┬ finalhandler@1.0.3
│ │ ├── debug@2.6.7
│ │ └── unpipe@1.0.0
│ ├── fresh@0.5.0
│ ├── merge-descriptors@1.0.1
│ ├── methods@1.1.2
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ ├── parseurl@1.3.1
│ ├── path-to-regexp@0.1.7
│ ├─┬ proxy-addr@1.1.4
│ │ ├── forwarded@0.1.0
│ │ └── ipaddr.js@1.3.0
│ ├── qs@6.4.0
│ ├── range-parser@1.2.0
│ ├─┬ send@0.15.3
│ │ ├── debug@2.6.7
│ │ ├── destroy@1.0.4
│ │ └── http-errors@1.6.1
│ ├── serve-static@1.12.3
│ ├── setprototypeof@1.0.3
│ ├── statuses@1.3.1
│ ├─┬ type-is@1.6.15
│ │ └── media-typer@0.3.0
│ ├── utils-merge@1.0.0
│ └── vary@1.1.1
├─┬ react@0.14.9
│ ├─┬ envify@3.4.1
│ │ └─┬ jstransform@11.0.3
│ │   ├── base62@1.2.0
│ │   ├── esprima-fb@15001.1.0-dev-harmony-fb
│ │   ├── object-assign@2.1.1
│ │   └── source-map@0.4.4
│ └─┬ fbjs@0.6.1
│   ├─┬ loose-envify@1.3.1
│   │ └── js-tokens@3.0.1
│   ├─┬ promise@7.1.1
│   │ └── asap@2.0.5
│   ├── ua-parser-js@0.7.12
│   └── whatwg-fetch@0.9.0
├── react-dom@0.14.9
├─┬ webpack@1.15.0
│ ├── acorn@3.3.0
│ ├── async@1.5.2
│ ├── clone@1.0.2
│ ├─┬ enhanced-resolve@0.9.1
│ │ └── memory-fs@0.2.0
│ ├── interpret@0.6.6
│ ├─┬ memory-fs@0.3.0
│ │ ├─┬ errno@0.1.4
│ │ │ └── prr@0.0.0
│ │ └─┬ readable-stream@2.2.11
│ │   ├── core-util-is@1.0.2
│ │   ├── isarray@1.0.0
│ │   ├── process-nextick-args@1.0.7
│ │   ├── safe-buffer@5.0.1
│ │   ├── string_decoder@1.0.2
│ │   └── util-deprecate@1.0.2
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├─┬ node-libs-browser@0.7.0
│ │ ├── assert@1.4.1
│ │ ├─┬ browserify-zlib@0.1.4
│ │ │ └── pako@0.2.9
│ │ ├─┬ buffer@4.9.1
│ │ │ ├── base64-js@1.2.0
│ │ │ └── ieee754@1.1.8
│ │ ├─┬ console-browserify@1.1.0
│ │ │ └── date-now@0.1.4
│ │ ├── constants-browserify@1.0.0
│ │ ├─┬ crypto-browserify@3.3.0
│ │ │ ├── browserify-aes@0.4.0
│ │ │ ├── pbkdf2-compat@2.0.1
│ │ │ ├── ripemd160@0.2.0
│ │ │ └── sha.js@2.2.6
│ │ ├── domain-browser@1.1.7
│ │ ├── events@1.1.1
│ │ ├── https-browserify@0.0.1
│ │ ├── os-browserify@0.2.1
│ │ ├── path-browserify@0.0.0
│ │ ├── process@0.11.10
│ │ ├── punycode@1.4.1
│ │ ├── querystring-es3@0.2.1
│ │ ├── stream-browserify@2.0.1
│ │ ├─┬ stream-http@2.7.2
│ │ │ ├── builtin-status-codes@3.0.0
│ │ │ ├── to-arraybuffer@1.0.1
│ │ │ └── xtend@4.0.1
│ │ ├── string_decoder@0.10.31
│ │ ├─┬ timers-browserify@2.0.2
│ │ │ └── setimmediate@1.0.5
│ │ ├── tty-browserify@0.0.0
│ │ ├─┬ url@0.11.0
│ │ │ ├── punycode@1.3.2
│ │ │ └── querystring@0.2.0
│ │ ├─┬ util@0.10.3
│ │ │ └── inherits@2.0.1
│ │ └─┬ vm-browserify@0.0.4
│ │   └── indexof@0.0.1
│ ├─┬ optimist@0.6.1
│ │ ├── minimist@0.0.10
│ │ └── wordwrap@0.0.2
│ ├─┬ supports-color@3.2.3
│ │ └── has-flag@1.0.0
│ ├── tapable@0.1.10
│ ├─┬ uglify-js@2.7.5
│ │ ├── async@0.2.10
│ │ ├── uglify-to-browserify@1.0.2
│ │ └─┬ yargs@3.10.0
│ │   ├── camelcase@1.2.1
│ │   ├─┬ cliui@2.1.0
│ │   │ ├─┬ center-align@0.1.3
│ │   │ │ ├─┬ align-text@0.1.4
│ │   │ │ │ ├── longest@1.0.1
│ │   │ │ │ └── repeat-string@1.6.1
│ │   │ │ └── lazy-cache@1.0.4
│ │   │ └── right-align@0.1.3
│ │   ├── decamelize@1.2.0
│ │   └── window-size@0.1.0
│ ├─┬ watchpack@0.2.9
│ │ └── async@0.9.2
│ └─┬ webpack-core@0.6.9
│   ├── source-list-map@0.1.8
│   └── source-map@0.4.4
├─┬ webpack-dev-middleware@1.10.2
│ ├── memory-fs@0.4.1
│ └── mime@1.3.4
└─┬ webpack-dev-server@1.16.5
  ├─┬ compression@1.6.2
  │ ├── bytes@2.3.0
  │ ├── compressible@2.0.10
  │ ├─┬ debug@2.2.0
  │ │ └── ms@0.7.1
  │ └── on-headers@1.0.1
  ├── connect-history-api-fallback@1.3.0
  ├─┬ http-proxy-middleware@0.17.4
  │ ├─┬ http-proxy@1.16.2
  │ │ ├── eventemitter3@1.2.0
  │ │ └── requires-port@1.0.0
  │ ├─┬ is-glob@3.1.0
  │ │ └── is-extglob@2.1.1
  │ ├── lodash@4.17.4
  │ └─┬ micromatch@2.3.11
  │   ├─┬ arr-diff@2.0.0
  │   │ └── arr-flatten@1.0.3
  │   ├── array-unique@0.2.1
  │   ├─┬ braces@1.8.5
  │   │ ├─┬ expand-range@1.8.2
  │   │ │ └─┬ fill-range@2.2.3
  │   │ │   ├── is-number@2.1.0
  │   │ │   ├── isobject@2.1.0
  │   │ │   └─┬ randomatic@1.1.7
  │   │ │     ├─┬ is-number@3.0.0
  │   │ │     │ └── kind-of@3.2.2
  │   │ │     └── kind-of@4.0.0
  │   │ ├── preserve@0.2.0
  │   │ └── repeat-element@1.1.2
  │   ├─┬ expand-brackets@0.1.5
  │   │ └── is-posix-bracket@0.1.1
  │   ├── extglob@0.3.2
  │   ├── filename-regex@2.0.1
  │   ├─┬ kind-of@3.2.2
  │   │ └── is-buffer@1.1.5
  │   ├─┬ normalize-path@2.1.1
  │   │ └── remove-trailing-separator@1.0.2
  │   ├─┬ object.omit@2.0.1
  │   │ ├─┬ for-own@0.1.5
  │   │ │ └── for-in@1.0.2
  │   │ └── is-extendable@0.1.1
  │   ├─┬ parse-glob@3.0.4
  │   │ ├── glob-base@0.3.0
  │   │ └── is-dotfile@1.0.3
  │   └─┬ regex-cache@0.4.3
  │     ├── is-equal-shallow@0.1.3
  │     └── is-primitive@2.0.0
  ├── open@0.0.5
  ├─┬ serve-index@1.9.0
  │ └── batch@0.6.1
  ├─┬ sockjs@0.3.18
  │ ├─┬ faye-websocket@0.10.0
  │ │ └─┬ websocket-driver@0.6.5
  │ │   └── websocket-extensions@0.1.1
  │ └── uuid@2.0.3
  ├─┬ sockjs-client@1.1.4
  │ ├─┬ eventsource@0.1.6
  │ │ └─┬ original@1.0.0
  │ │   └─┬ url-parse@1.0.5
  │ │     └── querystringify@0.0.4
  │ ├── faye-websocket@0.11.1
  │ ├── json3@3.3.2
  │ └─┬ url-parse@1.1.9
  │   └── querystringify@1.0.0
  ├── stream-cache@0.0.2
  ├─┬ strip-ansi@3.0.1
  │ └── ansi-regex@2.1.1
  └── supports-color@3.2.3

npm WARN examples No repository field.

> @ examples /Users/omer/code/aphrodite/examples
> babel-node server.js

module.js:472
    throw err;
    ^

Error: Cannot find module 'inline-style-prefixer/static/createPrefixer'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/omer/code/aphrodite/src/generate.js:11:48)
    at Module._compile (module.js:571:32)
    at normalLoader (/Users/omer/code/aphrodite/examples/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/omer/code/aphrodite/examples/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "run" "examples"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ examples: `babel-node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ examples script 'babel-node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/omer/.npm/_logs/2017-06-15T02_30_10_563Z-debug.log
```

**Comment by xymostech** [comment]
Huh, interesting! Thanks for the report @omerzach It looks like the examples directory depends on the root aphrodite directory, so we assume that you've run `npm install` in the root directory. Can you try running `npm install` inside of the root aphrodite directory and then follow your steps, and see what happens?

Maybe we should add a pre-install hook to run `cd .. && npm install`?

**Comment by omerzach** [comment]
Looks like you need to both `npm install` and `npm run build` from the root Aphrodite directory. Either a preinstall hook or just a line in the README sound good :).

**Comment by HeyMarcy** [comment]
THANKS! 
i had the same issue
