### ISSUE TITLE
'Cannot convert undefined or null to object' when use css("style")

### ISSUE THREAD

**Issue by zjin0522** [Khan/aphrodite#282]
Hi 
My version is "aphrodite": "^1.2.5", I wrote a test to test what's the result render by css functionality from aphrodite, the code as follow:

```
import {StyleSheet, css} from 'aphrodite';
describe('AA', () => {
  test('css rendering', () => {
    const test = StyleSheet.create({
      red: {
        backgroundColor: 'red'
      }
    });
    console.log(css(test));
 });

});
```

Then i got error as follow, could you give me some kinds of suggestion what's wrong on this ?
```
TypeError: Cannot convert undefined or null to object
        at Function.keys (<anonymous>)
      at OrderedElements.addStyleType (node_modules/aphrodite/lib/ordered-elements.js:103:35)
      at generateCSS (node_modules/aphrodite/lib/generate.js:164:16)
      at injectStyleOnce (node_modules/aphrodite/lib/inject.js:192:47)
      at injectAndGetClassName (node_modules/aphrodite/lib/inject.js:303:5)
      at css (node_modules/aphrodite/lib/exports.js:146:54)
      at Object.<anonymous> (test/cutOrders/styles.test.js:31:36)

```
Thanks very much

**Comment by jlfwong** [comment]
Hi @zjin0522 

If you change:

`    console.log(css(test));`

to

`    console.log(css(test.red));`

Then I think that should solve that problem.

Hope that helps!

**Comment by zjin0522** [comment]
Thanks very much for the answer,  does that means i always need to wrap the css properties into some object? , how about  i change the code as follow?
```
describe('AA', () => {
  test('css rendering', () => {
    const test = StyleSheet.create({
      backgroundColor: 'red'
    });
    console.log(css(test));
  });
});
```
