### ISSUE TITLE
Server side rendering causes Cannot automatically buffer without a document

### ISSUE THREAD

**Issue by bartolkaruza** [Khan/aphrodite#33]
I'm having some trouble understanding what is causing this issue. I'm using aphrodite as the css inlining library in combination with [universal-redux](https://github.com/bdefore/universal-redux). Since adding aphrodite, everything is working fine in NODE_ENV=development, but started failing when running pre packed webpack builds in production.

I'm not able to decipher the meaning of the below message without some better understanding of the aphrodite internals. Perhaps someone could help me with a brief explanation of possible causes?

````
ERROR GENERATING ROOT COMPONENT [Error: Cannot automatically buffer without a document] Error: Cannot automatically buffer without a document
    at injectStyleOnce (/Users/bartolkaruza/Development/Projects/dmm/dmm-web/node_modules/aphrodite/lib/inject.js:90:23)
    at css (/Users/bartolkaruza/Development/Projects/dmm/dmm-web/node_modules/aphrodite/lib/index.js:73:33)
    at Header.render (Header.js:47:28)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/bartolkaruza/Development/Projects/dmm/dmm-web/node_modules/react/lib/ReactCompositeComponent.js:587:34)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/Users/bartolkaruza/Development/Projects/dmm/dmm-web/node_modules/react/lib/ReactCompositeComponent.js:607:32)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/bartolkaruza/Development/Projects/dmm/dmm-web/node_modules/react/lib/ReactCompositeComponent.js:220:30)
    at Object.ReactReconciler.mountComponent (/Users/bartolkaruza/Development/Projects/dmm/dmm-web/node_modules/react/lib/ReactReconciler.js:37:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/bartolkaruza/Development/Projects/dmm/dmm-web/node_modules/react/lib/ReactCompositeComponent.js:225:34)
    at Object.ReactReconciler.mountComponent (/Users/bartolkaruza/Development/Projects/dmm/dmm-web/node_modules/react/lib/ReactReconciler.js:37:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/bartolkaruza/Development/Projects/dmm/dmm-web/node_modules/react/lib/ReactMultiChild.js:241:44)
````

**Comment by montemishkin** [comment]
Possibly similar to https://github.com/Khan/aphrodite/issues/23?

Hope that helps :)

**Comment by xymostech** [comment]
Are you following the instructions in the readme to do server-side rendering? You need to wrap your rendering code in a call to `StyleSheetServer.renderStatic()` so that Aphrodite knows to not actually insert things into the document.

See #23 (thanks @montemishkin :) )

**Comment by montemishkin** [comment]
Actually, glancing at https://github.com/bdefore/universal-redux it might be the case that you are not responsible for the eventual call to `renderToString` (it is instead done internally by universal-redux).

I might be misinterpreting their README, but it looks like you'll need to implement a custom `renderer` to replace the provided one that you would otherwise grab from 

```js
import { renderer } from 'universal-redux'
```

**Comment by bartolkaruza** [comment]
@montemishkin It's correct, all of the rendering plumbing is handled by UR.
I've opened a PR that enables the use of Aphrodite with UR as you have mentioned. 
https://github.com/bdefore/universal-redux/pull/98
